# Generated by Django 5.2.2 on 2025-06-08 18:08

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('volume', models.FloatField(help_text='Объем руды на складе, т')),
                ('sio2', models.FloatField(help_text='Содержание SiO2 в %')),
                ('fe', models.FloatField(help_text='Содержание Fe в %')),
                ('area', django.contrib.gis.db.models.fields.PolygonField(help_text='WKT полигон склада', srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='TruckModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('max_load', models.FloatField(help_text='Максимальная грузоподъемность, т')),
            ],
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_number', models.CharField(blank=True, max_length=10, null=True)),
                ('current_load', models.FloatField(help_text='Текущий вес груза, т')),
                ('sio2', models.FloatField(help_text='Содержание SiO2 в %')),
                ('fe', models.FloatField(help_text='Содержание Fe в %')),
                ('unload_point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trucks.truckmodel')),
            ],
        ),
    ]
